# Encoding

In [5]:
# Tranform categorical variables from non numerical values to numerical values so that ML models can process it
import pandas as pd
import numpy as np
import os

In [6]:
os.chdir("C:\Abhishek\CRM\Self\Python\handson")
df2 = pd.read_csv("3_MV.csv")

In [7]:
df2
# We have "type","manufact","model" attributes as categorical variables

,# ID,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,resale_mv
0,1,Acura,Integra,16.919,16.360,Automobile,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,16.360000
1,2,Acura,TL,39.384,19.875,Automobile,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,19.875000
2,3,Acura,CL,14.114,18.225,Automobile,22.799,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,18.225000
3,4,Acura,RL,8.588,29.725,Automobile,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,29.725000
4,5,Audi,A4,20.397,22.255,Automobile,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,22.255000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,153,Volvo,V40,3.545,NaN,Automobile,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,15.281667
152,154,Volvo,S70,15.245,NaN,Automobile,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,15.790000
153,155,Volvo,V70,17.531,NaN,Automobile,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,15.790000
154,156,Volvo,C70,3.493,NaN,Automobile,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,29.910000
155,157,Volvo,S80,18.969,NaN,Automobile,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,20.301667

In [ ]:
# MODEL: Encoding treatmemt

In [8]:
df2["model"].value_counts()

Neon          2
Integra       1
Cutlass       1
Sentra        1
Altima        1
             ..
Expedition    1
Ranger        1
F-Series      1
Civic         1
S80           1
Name: model, Length: 155, dtype: int64

In [9]:
df2["model"].nunique()

155

In [10]:
df3=df2.drop("model",axis=1)
# Since MODEL is highly cardinal we have dropped it

In [11]:
df3

,# ID,manufact,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,resale_mv
0,1,Acura,16.919,16.360,Automobile,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,16.360000
1,2,Acura,39.384,19.875,Automobile,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,19.875000
2,3,Acura,14.114,18.225,Automobile,22.799,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,18.225000
3,4,Acura,8.588,29.725,Automobile,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,29.725000
4,5,Audi,20.397,22.255,Automobile,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,22.255000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,153,Volvo,3.545,NaN,Automobile,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,15.281667
152,154,Volvo,15.245,NaN,Automobile,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,15.790000
153,155,Volvo,17.531,NaN,Automobile,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,15.790000
154,156,Volvo,3.493,NaN,Automobile,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,29.910000
155,157,Volvo,18.969,NaN,Automobile,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,20.301667

In [ ]:
# TYPE: Encoding treatmemt

In [12]:
df2["type"].value_counts()

Automobile    116
Truck          40
Name: type, dtype: int64

In [13]:
df2["type"].nunique()

2

In [18]:
# Replace AUTOMOBILE by 1 and TRUCK by 0
df2["type_encoded"] = df2["type"].replace(to_replace=['Automobile','Truck'],value=[1,0])
df2

,# ID,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,resale_mv,type_encoded
0,1,Acura,Integra,16.919,16.360,Automobile,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,16.360000,1
1,2,Acura,TL,39.384,19.875,Automobile,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,19.875000,1
2,3,Acura,CL,14.114,18.225,Automobile,22.799,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,18.225000,1
3,4,Acura,RL,8.588,29.725,Automobile,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,29.725000,1
4,5,Audi,A4,20.397,22.255,Automobile,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,22.255000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,153,Volvo,V40,3.545,NaN,Automobile,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,15.281667,1
152,154,Volvo,S70,15.245,NaN,Automobile,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,15.790000,1
153,155,Volvo,V70,17.531,NaN,Automobile,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,15.790000,1
154,156,Volvo,C70,3.493,NaN,Automobile,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,29.910000,1
155,157,Volvo,S80,18.969,NaN,Automobile,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,20.301667,1

In [ ]:
# MANUFACT :

In [27]:
percentage_freq = df2["manufact"].value_counts()*100/len(df2)

In [24]:
df2["manufact"].nunique()

30

In [28]:
percentage_freq

Dodge            7.051282
Ford             7.051282
Toyota           5.769231
Chevrolet        5.769231
Mercedes-Benz    5.769231
Mitsubishi       4.487179
Nissan           4.487179
Volvo            3.846154
Pontiac          3.846154
Lexus            3.846154
Oldsmobile       3.846154
Mercury          3.846154
Chrysler         3.846154
Volkswagen       3.846154
Saturn           3.205128
Cadillac         3.205128
Honda            3.205128
Plymouth         2.564103
Acura            2.564103
Buick            2.564103
Audi             1.923077
Jeep             1.923077
Porsche          1.923077
Hyundai          1.923077
BMW              1.923077
Lincoln          1.923077
Saab             1.282051
Subaru           1.282051
Jaguar           0.641026
Infiniti         0.641026
Name: manufact, dtype: float64

In [31]:
# lets create a category to classify all manufact values having less than 2% of percentage frequence
df2["manufact_rare_wt"] = df2["manufact"].replace(to_replace=['Subaru','Jaguar','Saab','Ininiti'],value='others')

In [33]:
df2['manufact_rare_wt'].value_counts()

Dodge            11
Ford             11
Toyota            9
Chevrolet         9
Mercedes-Benz     9
Mitsubishi        7
Nissan            7
Lexus             6
Volkswagen        6
Pontiac           6
Oldsmobile        6
Mercury           6
Volvo             6
Chrysler          6
others            5
Honda             5
Cadillac          5
Saturn            5
Plymouth          4
Buick             4
Acura             4
Jeep              3
Audi              3
Lincoln           3
Hyundai           3
Porsche           3
BMW               3
Infiniti          1
Name: manufact_rare_wt, dtype: int64

In [34]:
manufact_mean = df2.groupby("manufact_rare_wt")["price"].mean()

In [35]:
manufact_mean

manufact_rare_wt
Acura            28.674750
Audi             39.980000
BMW              33.096667
Buick            26.781250
Cadillac         40.254000
Chevrolet        20.022778
Chrysler         23.430833
Dodge            24.213636
Ford             21.047273
Honda            20.277000
Hyundai          12.165667
Infiniti         29.465000
Jeep             20.991667
Lexus            44.055000
Lincoln          41.690000
Mercedes-Benz    52.916667
Mercury          20.748333
Mitsubishi       22.167429
Nissan           22.360714
Oldsmobile       25.622833
Plymouth         22.642500
Pontiac          22.949167
Porsche          62.473333
Saturn           14.271000
Toyota           21.982889
Volkswagen       17.698333
Volvo            30.933333
others           28.962000
Name: price, dtype: float64

In [37]:
# Need to MAP the manufact_mean to each category
df2["manufact_en"]=df2["manufact_rare_wt"].map(manufact_mean)

In [38]:
df2

,# ID,manufact,model,sales,resale,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,resale_mv,type_encoded,manufact_rare_wt,manufact_en
0,1,Acura,Integra,16.919,16.360,Automobile,21.500,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,16.360000,1,Acura,28.674750
1,2,Acura,TL,39.384,19.875,Automobile,28.400,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,19.875000,1,Acura,28.674750
2,3,Acura,CL,14.114,18.225,Automobile,22.799,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,18.225000,1,Acura,28.674750
3,4,Acura,RL,8.588,29.725,Automobile,42.000,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,29.725000,1,Acura,28.674750
4,5,Audi,A4,20.397,22.255,Automobile,23.990,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,22.255000,1,Audi,39.980000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,153,Volvo,V40,3.545,NaN,Automobile,24.400,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,15.281667,1,Volvo,30.933333
152,154,Volvo,S70,15.245,NaN,Automobile,27.500,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,15.790000,1,Volvo,30.933333
153,155,Volvo,V70,17.531,NaN,Automobile,28.800,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,15.790000,1,Volvo,30.933333
154,156,Volvo,C70,3.493,NaN,Automobile,45.500,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,29.910000,1,Volvo,30.933333
155,157,Volvo,S80,18.969,NaN,Automobile,36.000,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,20.301667,1,Volvo,30.933333

In [40]:
df2.to_csv("4_EN_Ab.csv",index=False)

In [ ]:
# SKLearn also can be used to do Encoding for OneHotEncoder, LabelEncoder, OrdinalEncoding